export const COUNTRY_NAMES = {
  US: "Estados Unidos",
  JP: "Japón",
  ES: "España",
  MX: "México",
  CO: "Colombia",
  PE: "Perú",
  BR: "Brasil",
  CL: "Chile",
  FR: "Francia",
  GB: "Reino Unido",
  AR: "Argentina",
  CR: "Costa Rica",
  PA: "Panamá",
  DO: "Rep. Dominicana",
  PR: "Puerto Rico",
  IT: "Italia",
  DE: "Alemania",
  NL: "Países Bajos",
  AE: "Emiratos",
  KR: "Corea del Sur",
  SG: "Singapur",
  TH: "Tailandia",
  AU: "Australia",
  CA: "Canadá"
};

export const COUNTRY_FLAG = {
  US: "🇺🇸",
  JP: "🇯🇵",
  ES: "🇪🇸",
  MX: "🇲🇽",
  CO: "🇨🇴",
  PE: "🇵🇪",
  BR: "🇧🇷",
  CL: "🇨🇱",
  FR: "🇫🇷",
  GB: "🇬🇧",
  AR: "🇦🇷",
  CR: "🇨🇷",
  PA: "🇵🇦",
  DO: "🇩🇴",
  PR: "🇵🇷",
  IT: "🇮🇹",
  DE: "🇩🇪",
  NL: "🇳🇱",
  AE: "🇦🇪",
  KR: "🇰🇷",
  SG: "🇸🇬",
  TH: "🇹🇭",
  AU: "🇦🇺",
  CA: "🇨🇦"
};
